import { cleanEnv, str, num } from 'envalid';

export const env = cleanEnv(process.env, {
  NODE_ENV: str({ choices: ['development', 'production', 'test'], default: 'development' }),
  PORT: num({ default: 5000 }),
  DATABASE_URL: str(),
  JWT_SECRET: str(),
  JWT_EXPIRES_IN: str({ default: '7d' }),
  RAZORPAY_KEY_ID: str({ default: '' }),
  RAZORPAY_KEY_SECRET: str({ default: '' }),
  SMTP_HOST: str({ default: '' }),
  SMTP_PORT: num({ default: 587 }),
  SMTP_USER: str({ default: '' }),
  SMTP_PASS: str({ default: '' }),
  EMAIL_FROM: str({ default: 'noreply@waderaassociates.com' }),
  AWS_ACCESS_KEY_ID: str({ default: '' }),
  AWS_SECRET_ACCESS_KEY: str({ default: '' }),
  AWS_REGION: str({ default: 'ap-south-1' }),
  AWS_BUCKET_NAME: str({ default: '' }),
  EXCHANGE_RATE_API_KEY: str({ default: '' }),
  EXCHANGE_RATE_API_URL: str({ default: 'https://api.exchangerate-api.com/v4/latest/INR' }),
  GEOLOCATION_API_KEY: str({ default: '' }),
  GEOLOCATION_API_URL: str({ default: 'https://api.ipgeolocation.io/ipgeo' }),
  FRONTEND_URL: str({ default: 'http://localhost:3000' }),
  REDIS_URL: str({ default: 'redis://localhost:6379' }),
  DEVELOPER_ADMIN_EMAIL: str({ default: 'admin@waderaassociates.com' }),
  DEVELOPER_ADMIN_PASSWORD: str({ default: 'ChangeMe@123' }),
  LOG_LEVEL: str({ default: 'info' }),
});
